---
title: "PCAdapt Final Run"
author: "Jack Poole"
date: "2026-4-2"
output: html_document
---

```{r}
library(vcfR)
library(bigsnpr)
library(ggplot2)
library(dplyr)
library(qvalue)
library(stringr)
library(pcadapt)
```


# This should result in a filtered .bed, .bim, and .fam
```{r}
plink_path <- "/usr/bin/plink"

#Sets the output file prefix
sub_name = "n218_geno_10"

#Threshold for calling outliers
alpha = 0.05


# Convert to PLINK BED, which is needed for SNP clumping in the next step
system(paste(plink_path, "--vcf ../Preprocessing/n218_filtered_snps_geno_10_clumped.recode.vcf",
  "--allow-extra-chr",
  "--make-bed",
  "--out", paste0(sub_name)))

# This function is creating a matrix using the functionG command in the bigsnpr package
toMatrix <- function(G){
  Gm = matrix(nrow=length(G[,1]), ncol=length(G[1,]))
  for(i in seq(length(G[,1]))){
    Gm[i,]=G[i,]
  }
  return(Gm)
}
```
# Part 1 - create the scree plot to know how to many PCs to use
```{r}

#A .bk file is a temporary backing file - our tools downstream will generate them.
#This step makes sure there's no leftover .bk files that may cause conflicts
f_bk = paste0(sub_name, ".bk")
if (file.exists(f_bk)) {
  #Delete file if it exists
  file.remove(f_bk)
}

  snp_readBed(paste0(sub_name, ".bed"))
  # this will create a .rds file
  obj.bigSNP <- snp_attach(paste0(sub_name, ".rds"))
  #Assign the genotype, snp, chromosome, and position of the snps into one matrix for use latter
  G <- obj.bigSNP$genotypes
  SNPs <- obj.bigSNP$map$marker.ID
  CHR  <- as.integer(as.factor(obj.bigSNP$map$chromosome))
  POS <- obj.bigSNP$map$physical.pos
  
  # check if there is any missing values as NA
  #big_counts(G, ind.col = 1:dim(G)[1]) # normally the data include missing values
  # genotype imputation
  G <- snp_fastImputeSimple(G, method = c("mean0"), ncores = 8) # mean0 is based on rounded mean
  #big_counts(G, ind.col = 1:dim(G)[1]) # check if NAs are 0
  # LD clumping using r2 = 0.2
  newpc <- big_SVD(G, fun.scaling = snp_scaleBinom(), k = 10) # size is the window size of 10K
  
  
  print(paste0("SNPs loaded: ", length(SNPs)))
  
  
  # Part 2 - population structure via pcadapt
  file <- read.pcadapt(paste0(sub_name, ".bed"), type = "bed")
  bim_file <- read.delim(paste0(sub_name, ".bim"), header = FALSE, sep = "\t")
  # Scree plot
  x <- pcadapt(input = file, K = 10)
  # The eigenvalues that correspond to random variation lie on a straight line whereas the ones that correspond to population structure lie on a steep curve. It is recommended to keep PCs that correspond to eigenvalues to the left of the straight line (Cattell’s rule).
  scree_plot <- plot(x, option = "screeplot")
  # Score plot: another option to choose the number of PCs is based on the ‘score plot’ that displays population structure.
 # sample_file = read.delim(paste0(sub_name,"_list.txt"), header = TRUE, sep='\t')
 # poplist.names <- sample_file$Pop
  # PCA plot
  PCA_plot <- plot(x, option = "scores", i=1, j=2)

PCA_plot

#Once again, use this plot to find the minimum number of PCs by choosing the the PC left of the flatish line
scree_plot
```
# CHANGE THE NUMBER OF PCs BASED ON THE SCREE PLOT
```{r}
#This value should be set to the last PC before the scree plot starts to level off.
PC_value = 3
```


# part 2 Best practise for outlier detection

```{r}

  Gm = toMatrix(G)
  G_coded = add_code256(big_copy(Gm, type="raw"), code=bigsnpr:::CODE_012)
  
  # eliminate monomorphic SNPs
  Gm = Gm[,snp_MAF(G_coded) != 0] 
  
  #Put it back to normal after eliminating monomorphic SNPs
  G_coded = add_code256(big_copy(Gm, type="raw"), code=bigsnpr:::CODE_012)
  
  #This is where pcadapt is going to run and give us our outlier predictions. The PC_value is used as the last PC in the range that it should be evaluating the SNPs against
  res_pcadapt <- snp_gc(snp_pcadapt(G_coded, U.row = newpc$u[,1:PC_value])) 
  
  #Make  histogram of the p-values we just generated from pcadapt
  res_p <- predict(res_pcadapt,log10 = F)
  hist(res_p, xlab = "p-values", main = NULL, breaks = 50, col = "orange")
  
  # Choosing a cutoff for outlier detection
  qval <- qvalue(res_p)$qvalues
  #Assigns SNPs as outliers if they have qvalues less than the alpha threshold
  outliers <- which(qval < alpha)
  print(paste0("number of outliers from best practise in ", sub_name, " is: ", length(outliers)))
  
  
  #Making a manhattan plot
  CHR = CHR[which(snp_MAF(G_coded) != 0)]
  POS = POS[which(snp_MAF(G_coded) != 0)]
  daf = data.frame(CHR=CHR, POS=POS, SNP=paste0(CHR,"_",POS), Ps=res_p, qvalue=qval)
  outlier_SNP <- paste0(CHR[outliers],'_',POS[outliers])
  outlier_daf <- data.frame(CHR=CHR[outliers], POS=POS[outliers], POS=POS[outliers], snp_id=outlier_SNP)
  write.table(outlier_daf, file = paste0(sub_name, "_PCAdapt_BP_q05_n_", length(outliers), ".bed"), sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
  #jpeg("Mahattan_Ind509_best_practice_outlier_PC1-2_10K.jpg", width = 16, height = 9, units = 'in', res = 300)
  # customize mahattan plot see https://www.r-graph-gallery.com/101_Manhattan_plot.html
  don <- daf %>% 
    dplyr::group_by(CHR) %>% 
    dplyr::summarise(chr_len=max(POS)) %>% 
    mutate(tot=cumsum(chr_len)-chr_len) %>%
    dplyr::select(-chr_len) %>% 
    left_join(daf, ., by=c("CHR"="CHR")) %>%
    arrange(CHR, POS) %>%
    mutate(BPcum=POS+tot) %>%
    mutate(is_highlight=ifelse(SNP %in% outlier_SNP, "yes", "no"))
  axisdf = don %>% dplyr::group_by(CHR) %>% dplyr::summarize(center=( max(BPcum) + min(BPcum) ) / 2 )
  write.table(don, file = paste0(sub_name, "_qs.txt"), sep = "\t", quote = FALSE, row.names = FALSE, col.names = TRUE)

outlier_plot <- ggplot(don, aes(x=BPcum, y=-log10(qvalue))) +
    geom_point(aes(color=as.factor(CHR)), alpha=0.8, size=0.5) +
    scale_color_manual(values = rep(c("grey", "#4F4F4F"), 22)) +
    scale_x_continuous(label = axisdf$CHR, breaks = axisdf$center) +
    scale_y_continuous(expand = c(0, 0.2)) +
    geom_point(data=subset(don, qvalue < 0.05), color="red", size=0.8) +
    xlab("Scaffold (pcadapt association with population structure)") +
    ylab("-log10(q-value)") +
    theme_bw() +
    theme(
      legend.position="none",
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank()
    )
outlier_plot

#Turn the outliers into a csv format as the output to merge with OutFLANK
outlier_full <- daf[outliers, ] 
write.csv(outlier_full, file = paste0(sub_name, "_pcadapt_outliers.csv"),
          row.names = FALSE)
```
